[prune]
  non-go = true
  go-tests = true
  unused-packages = true


[[constraint]]
  branch = "master"
  name = "github.com/andreburgaud/crypt2go"

[[constraint]]
  name = "github.com/manifoldco/promptui"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  branch = "master"
  name = "github.com/olekukonko/tablewriter"

[[constraint]]
  name = "github.com/spf13/cobra"
  branch = "master"

[[constraint]]
  name = "github.com/spf13/viper"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/stellar/go"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sync"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"
